name: Open Pull Request with updated stats report
on:
    workflow_run:
      workflows: ["Test Learning Path"]
      types: [completed]
permissions:
  actions: read
  contents: write
  pull-requests: write
jobs:
  stats-pr:
    runs-on: arm-linux-runner
    steps:
        - name: Checkout main branch
          uses: actions/checkout@v2
          with:
            ref: main
        - name: Download stats report as artifact
          uses: actions/download-artifact@v4
          with:
            # Run ID of the workflow that uploaded the artifact
            run-id: ${{ github.event.workflow_run.id }}
            path: data/
            github-token: ${{ github.token }}
        - name: Move stats file
          # Unpack the artifact and move the stats file to the correct location
          run: |
              mv stats_current_test_info/stats_current_test_info.yml data/stats_current_test_info.yml
              rm -rf stats_current_test_info
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6
          if: success()
          with:
            commit-message: Update stats_current_test_info.yml
            title: Update stats_current_test_info.yml
            body: |
              Update test result file with recent run
              Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
            branch: update-stats-current-test-info
            base: main
