name: Test Learning Path
on: push
jobs:
  Test-Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: Run test suite for all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: ./.github/workflows/test_lp.sh ${ALL_CHANGED_FILES}