name: Test Learning Path
on: pull_request
jobs:
  Test-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.md

      - name: Install dependencies
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        run: pip install -r tools/requirements.txt

      - name: Run test suite for all changed files
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        run: ./.github/workflows/test_lp.sh ${{ steps.changed-markdown-files.outputs.all_changed_files }}