name: Test Learning Path
on: push
jobs:
  Test-Suite:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: bash ./.github/workflows/test_lp.sh ${{ github.workspace }}
